[package]
name = "dt-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5.11"
gethostname = "0.2.1"
glob = "0.3.0"
log = "0.4.14"
path-clean = "0.1.0"
serde = { version = "1.0.130", features = ["derive"] }
shellexpand = "2.1.0"
toml = "0.5.8"

# Author: Blurgy <gy@blurgy.xyz>
# Date:   Sep 17 2021, 21:32 [CST]
