[workspace]
members = [
    "dt-cli",
    "dt-core",
    "dt-server",
]

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

# Author: Blurgy <gy@blurgy.xyz>
# Date:   Sep 17 2021, 21:19 [CST]
