[[local]]
name = "wubba lubba dub dub"
basedir = "~"
sources = []
target = "."

[[local]]
name = "gubba nub nub doo rah kah"
basedir = "~"
sources = []
target = "."

[[local]]
name = "wubba lubba dub dub"
basedir = "~"
sources = []
target = "."
