[package]
name = "dt-server"
description = "Syncing dotfiles and more"
version = "0.1.0"
edition = "2018"
authors = ["Gaoyang Zhang <gy@blurgy.xyz>"]
documentation = "https://dt-cli-docs.blurgy.xyz/"
license = "MIT OR Apache-2.0"
repository = "https://github.com/blurgyy/dt"
categories = ["command-line-utilities", "config"]
keywords = ["dotfiles", "manager", "syncing", "config"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5.11"
dirs = "4.0.0"
dt-core = { path = "../dt-core", version = "0.2.1" }
log = "0.4.14"
pretty_env_logger = "0.4.0"
structopt = "0.3.23"
tokio = { version = "1.12.0", features = ["full"] }
warp = "0.3.1"

# Author: Blurgy <gy@blurgy.xyz>
# Date:   Oct 19 2021, 09:35 [CST]
