[[local]]
# Explanation:
#   - "*":      All files without leading dot.
#   - ".[!.]*": All files with a single leading dot.
#   - "..?*":   All files with double (or more) leading dots.
basedir = "~"
sources = ["*", ".[!.]*", "..?*"]
target = "../testroot"
