[[local]]
name = "placeholder"
hostname_sep = "@@"

basedir = "../testroot/items/no_per_host_items"
sources = ["*", "authorized_keys@@watson"]
target = "../testroot/items/no_per_host_items/target"

allow_overwrite = true
method = "Copy"
