on:
  push:
    tags:
      - 'v*.*.*'

name: release

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Compile dt-cli
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features --locked
    - name: Fetch all tags
      run: git fetch origin +refs/tags/*:refs/tags/*
    - name: Get name of current tag
      id: get_tag_name
      run: echo "::set-output name=tag_name::${GITHUB_REF/refs\/tags\//}"
    - name: Generate changelog
      uses: orhun/git-cliff-action@v1
      id: git-cliff
      with:
        args: -vv --latest --strip header
      env:
        OUTPUT: CHANGELOG.md
    - name: Set release body
      id: changelog
      run: |
        if log=$(cat ${{ steps.git-cliff.outputs.changelog }}); then
          log="${log//'%'/'%25'}"
          log="${log//'~'/\\~}"
          log="${log//$'\n'/'%0A'}"
          log="${log//$'\r'/'%0D'}"
          echo "::set-output name=release_body::$log"
        else
          echo "::set-output name=release_body::log generation failed"
        fi
    - name: Strip debug symbols
      run: |
        strip target/release/dt-cli
    - name: Create release with compiled binary
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        prerelease: false
        tag_name: ${{ github.ref }}
        name: Release ${{ steps.get_tag_name.outputs.tag_name }}
        body: ${{ steps.changelog.outputs.release_body }}
        files: |
          target/release/dt-cli
          LICENSE-APACHE
          LICENSE-MIT

# Author: Blurgy <gy@blurgy.xyz>
# Date:   Oct 07 2021, 00:39 [CST]
