on:
  push:
    branches:
      - main

name: tests

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run unit tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --all-features --locked

# Author: Blurgy <gy@blurgy.xyz>
# Date:   Oct 07 2021, 00:39 [CST]
