on:
  push:
    branches:
      - "**" # All branches

jobs:
  run:
    name: Check typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v2
      - name: Check typos in source code
        uses: crate-ci/typos@master
        with:
          config: ./.github/workflows/_typos.toml

      - name: Checkout Actions Repository
        uses: actions/checkout@v2
        with:
          ref: docs
      - name: Check typos in documentation
        uses: crate-ci/typos@master
        with:
          config: ./.github/workflows/_typos.toml
